mozilla-services/contile

src/adm/filter.rs, src/adm/mod.rs, src/adm/tiles.rs, src/web/test.rs
Client begins working -- it expects `url`
Closes #110
=> fix: advertiser_url -> url in the response

src/adm/filter.rs, src/adm/tiles.rs, src/server/cache.rs, src/server/location.rs, src/settings.rs, src/web/handlers.rs, src/web/test.rs
Use `CONTILE_DEFAULT_LOCATION` to specify a default location other
than `USOK`.
includes unit test
Closes #95
=> feat: use default location for unlocatable IPs

CODE_OF_CONDUCT.md
Signed version of #119 
N/A
N/A
=> doc: add Code of Conduct file

.gitignore, src/adm/settings.rs, tools/test/integration_test.py, tools/test/requirements.txt, tools/test/test_data/bad_adv.json, tools/test/test_data/bad_click.json, tools/test/test_data/default.json
Add missing integration test python script, and support files. (Guessing one of the many merges dropped these).
See `.tools/test/README.md`
Closes #60
=> feat: Add integration tests

tools/test/README.md
Update the PIP install command and added the python3 command.
It's just doc update so no testing required.
┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/CONSVC-171)
=> docs(README): update a few commands for integration test

tools/test/integration_test.py
No functional changes. I used isort and black to reformat the code
┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/CONSVC-169)
=> Reformat integration test file

src/metrics.rs, src/tags.rs
removes two unneeded tags from metrics
testing included
Closes #136
=> feat: Remove useless metric tags

src/web/handlers.rs
I'm working on a separate PR that refactors location lookup into a separate extractor, then we can more easily add unit tests for this.
Issue #149
=> feat: get the client IP for mmdb from X-Forwarded-For

src/adm/tiles.rs, src/server/cache.rs, src/web/handlers.rs
and some naming cleanup
Closes #138
=> feat: metric calls to adM

src/adm/filter.rs, src/adm/mod.rs, src/adm/tiles.rs, src/server/mod.rs, src/settings.rs, src/web/extractors.rs, src/web/handlers.rs, src/web/mod.rs, src/web/test.rs, src/web/user_agent.rs
and cleanup the extractors
Closes #195
=> refactor: kill the unused old adM API code

src/server/cache.rs, src/web/handlers.rs, src/web/test.rs
new integration test passes
Closes #191
=> fix: return 204 no contents for cache hits 

.circleci/config.yml, .gitignore, docker-compose.yml, tools/volumes/client/scenarios.yml, tools/volumes/contile/adm_settings.json, tools/volumes/partner/responses.yml
`Automated the process of running the integration tests to trigger the CircleCI workflow. Below are the changes made:`
`- integrated CircleCI workflow with the integration tests in the Contile repo to trigger the workflow`
`- added a `docker-compose.yml` file with the image details for Partner, Client and Contile`
`- added `/volumes` folder where the test `scenarios.yml`, `responses.yml` and `adm_settings.json` files resides required to run the tests`
`- updated the CircleCI `config.yml` file with the necessary steps to run the integration tests with commands`
@mozilla-services/context-services - Please review the files added together with the commands. Thanks!
=> test(Integration_test): add integration test to the CircleCI workflow

.circleci/config.yml, Dockerfile, docker-compose.yml, src/server/img_storage.rs, tools/volumes/client/scenarios.yml
This pull request updates the `Dockerfile` for contile to make sure that the build and run environments are the same version and updates the CI workflow configuration as well as test scenarios for the integration tests in order to resolve the failures observed in #223.
This pull request can be tested by checking the CircleCI checks for failures.
=> Fix integration tests

src/adm/filter.rs, src/adm/settings.rs, src/web/handlers.rs, src/web/mod.rs, src/web/test.rs
don't bother w/ the cache layer or querying adM, they always 204
New unit test added
Closes #226
=> feat: optimize handling of not included countries

src/server/img_storage.rs
=> feat: don't create the cloud storage bucket by default

src/server/img_storage.rs
* remove unused code
* added comment describing bucket properties
* removed unused setting
* changed function name to `check_bucket`
How should reviewers test?
Closes [link](link).
=> chore: cleanup bucket creation

Cargo.lock, Cargo.toml, src/server/img_storage.rs
so we only issue writes when the object doesn't already exist, avoiding rate
limiting errors
This supersedes the bits of #258 adding the precondition check
Please run the img_storage tests with a test bucket setup
Closes #259
=> feat: add a cloud storage write precondition

src/server/location.rs, src/web/test.rs
=> feat: support dma-codes in location_test_header

src/error.rs, src/server/img_storage.rs, src/server/mod.rs, src/settings.rs
adding a HandlerKind::CloudStorage variant
and set a connect_timeout for reqwest client
An example of the new event: https://sentry.prod.mozaws.net/operations/contile/issues/12570630/
Closes #263
Closes #253
=> feat: don't hide cloud storage update errors

src/settings.rs, src/web/handlers.rs, src/web/test.rs
new unit tests passing
Closes #284
=> feat: optionally send 200 OK empty responses to excluded countries

smoke-tests/runner/main.py, smoke-tests/runner/requirements.txt
@dlactin figured out why the runner function fails to trigger the client functions.
This pull request from the main repo replaces #382 because we don't run CI for forks, which means the other pull request is blocked from merging.
=> Update geolocation smoke-test runner

src/adm/filter.rs, src/adm/tiles.rs, src/web/handlers.rs, src/web/test.rs, src/web/user_agent.rs
=> feat: add tags to ADM errors.

Cargo.lock, Cargo.toml, Dockerfile, src/adm/filter.rs, src/adm/settings.rs, src/adm/tiles.rs, src/error.rs, src/logging.rs, src/metrics.rs, src/server/cache.rs, src/server/img_storage.rs, src/server/location.rs, src/server/mod.rs, src/settings.rs, src/tags.rs, src/web/dockerflow.rs, src/web/extractors.rs, src/web/handlers.rs, src/web/middleware/sentry.rs, src/web/test.rs
- move to the latest cloud-storage (w/ a new API)
- upgrade cadence, requiring wrapping of its Client in Arc
- fix the 404 response to use the standard json payload
Closes #386
=> feat: upgrade to actix-web 4

src/web/handlers.rs, src/web/test.rs
=> fix: don't panic gen_range with an empty range

src/error.rs, src/web/handlers.rs
=> feat: move common connect/timeout errors from sentry to metrics

src/adm/filter.rs, src/server/mod.rs
I think this would achieve getting metrics for unsuccessful updates?
=> [CONSVC-2023] feat: metrics for bucket reads/updates

src/adm/filter.rs
This fixes [DISCO-2188](https://mozilla-hub.atlassian.net/browse/DISCO-2188).
[DISCO-2188]: https://mozilla-hub.atlassian.net/browse/DISCO-2188?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DISCO-2188] fix: resolve the deadlock in the filter updater

CHANGELOG.md, Cargo.lock, Cargo.toml, test-engineering/contract-tests/volumes/client/scenarios.yml, test-engineering/contract-tests/volumes/client/scenarios_tiles_cache.yml
Release highlight:
- Return HTTP 204 for unknown form-factors
=> chore: tag 1.11.0

PULL_REQUEST_TEMPLATE.md
JIRA: [DISCO-2370](https://mozilla-hub.atlassian.net/browse/DISCO-2370)
GitHub: #534 
Proposal to add a PR template to this project. All ideas, modifications and suggestions welcome!
[DISCO-2370]: https://mozilla-hub.atlassian.net/browse/DISCO-2370?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DISCO-2370] Add pull request template to Contile

README.md
JIRA: [DISCO-2280](https://mozilla-hub.atlassian.net/browse/DISCO-2280)
GitHub: [#TODO](https://github.com/mozilla-services/contile/issues/TODO)
Test to ensure https://mozilla-hub.atlassian.net/browse/DISCO-2280 `[do not deploy]` feature functions as expected.
[DISCO-2280]: https://mozilla-hub.atlassian.net/browse/DISCO-2280?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DISCO] Contile test do not deploy [do not deploy]

README.md
JIRA: [DISCO-TODO](https://mozilla-hub.atlassian.net/browse/DISCO-TODO)
GitHub: [#TODO](https://github.com/mozilla-services/contile/issues/TODO)
Pipeline test for [do not deploy]
=> test [do not deploy]

src/adm/filter.rs, src/adm/settings.rs, src/lib.rs, src/server/cache.rs, src/server/mod.rs, src/settings.rs, src/sov/mod.rs, src/web/handlers.rs, src/web/test.rs, test-engineering/contract-tests/client/tests/client_models.py, test-engineering/contract-tests/client/tests/conftest.py, test-engineering/contract-tests/client/tests/test_contile.py, test-engineering/contract-tests/docker-compose.yml, test-engineering/contract-tests/volumes/client/scenarios.yml, test-engineering/contract-tests/volumes/client/scenarios_tiles_cache.yml, test-engineering/contract-tests/volumes/contile/sov_settings.json
JIRA: [DISCO-2311](https://mozilla-hub.atlassian.net/browse/DISCO-2311)
Added intake of SOV json, encoded json into a string and passed it into the tiles/ endpoint
[DISCO-2311]: https://mozilla-hub.atlassian.net/browse/DISCO-2311?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DISCO-2311] feat: SOV components for Contile [load test: warn]

README.md, test-engineering/contract-tests/client/tests/conftest.py, test-engineering/contract-tests/poetry.lock, test-engineering/contract-tests/pyproject.toml, test-engineering/load/poetry.lock, test-engineering/load/pyproject.toml
JIRA: N/A
GitHub: N/A
- Update dependencies for contract and load tests. This will resolve PRs:
- https://github.com/mozilla-services/contile/pull/577
- https://github.com/mozilla-services/contile/pull/570
- https://github.com/mozilla-services/contile/pull/566
- https://github.com/mozilla-services/contile/pull/565
- Update Grafana dashboard link in README
=> Test Engineering Dependency Update [load test: abort]

.circleci/config.yml
This is an empty commit (with a change in hash, so it'll trigger a new build) that I will use to show how Continuous Deployment works in the CPR meeting this evening. I just need an approval so that I can merge this shortly before the presentation.
=> Empty Commit for CPR presentation

.github/CODEOWNERS
JIRA: [DISCO-2590](https://mozilla-hub.atlassian.net/browse/DISCO-2590)
[DISCO-2590]: https://mozilla-hub.atlassian.net/browse/DISCO-2590?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: Add a new code owner for the ads team
