mozilla-services/contile

src/adm.rs, src/error.rs, src/web/handlers.rs
ADM can sometimes return invalid content (e.g. a 200 response with no
"tiles".
Report this to sentry, and log, but we return an "empty" value to the
client.
A bit difficult, since this will query the ADM service directly. It's possible to use an external service which returns an invalid response value (e.g. 
```
echo -e "HTTP/1.1 200\ncontent-length:2\content-type:application/json\n\n{}" | nc -l -p 8080 
```
and set the `CONTILE_ADM_ENDPOINT="http://localhost:8080"`
*Note, this is an example only. the response may not be fully valid HTTP
Closes #55
=> bug: handle bad responses from ADM

src/adm.rs, src/server/cache.rs, src/server/location.rs, src/web/handlers.rs, src/web/mod.rs, src/web/user_agent.rs
- specify form-factor & os-family
- fixup region-code & handling of GCP load balancer's
"client_region_subdivision" format
- hardcode placement to "newtab"
This is a quick fix -- to be tested on the dev env deployment
Closes #77
=> fix: quick fixes to support the new adM API

src/web/extractors.rs, src/web/handlers.rs
Closes: #83
Make the URI `country` and `placement` parameters optional 
If not specified. the country should default to the origin IP address (or US if no `REMOTE_ADDR` header is present) and placement should default to `None`
Closes #83.
=> feat: Make "country" and "placement" optional args

src/adm/filter.rs, src/adm/tiles.rs, src/server/cache.rs, src/server/location.rs, src/web/mock_adm_response1.json, src/web/test.rs
- click_url's aespFlag parameter is deprecated
- note os-family isn't currently for targeting
- include more metadata in sentry errors
Fixes dev/stage to return tiles
Closes #96
=> feat: minor updates per the latest Tiles API

src/server/location.rs, src/settings.rs, src/web/handlers.rs
Closes #101
This adds a new setting: `location_test_header` which can be used to
specify a custom, testing location request header (e.g. `Test-Location`
which can contain a false test location for the request. This flag is
not meant for use in a production environment. If the header is not
present, the server will fall back on the normal location determination
code.
unit test included.
Closes #101
=> feat: Add a setting which defines a custom location header

src/adm/tiles.rs, src/error.rs, src/web/handlers.rs, src/web/test.rs
Closes: #92
Add improved response codes:
200 - tiles included
204 - No tile content included
502 - ADM returned a 500 
503 - ADM returned a general error
Unit test included
Issue #92
=> feat: Add improved response codes

src/adm/filter.rs, src/adm/settings.rs, src/web/test.rs
allow partial matching to the domains specified in the inclusion filter
e.g. "click_hosts": ["example.com"] now allows "foo.example.com"
How should reviewers test?
Closes #109
=> feat: relax click/impression host checking

Cargo.lock, Cargo.toml
until our onpremise sentry is upgraded:
https://github.com/getsentry/sentry-rust/issues/277
and ensure stack traces in sentry get line numbers
/\_\_error\_\_ reports to sentry
Closes #111
=> fix: pin sentry to 0.19

src/adm/tiles.rs
and log an error! for these (for now) so they show up in our stage/prod logs
Not easy to test this currently, we already return an empty response to the client. We can test this this change if we mock out sentry and allow feedback from it for tests
Closes #116
=> feat: don't fail to decode on adM's empty response

src/error.rs, src/web/handlers.rs, src/web/mod.rs, src/web/user_agent.rs
Closes: #124
Exclude non-firefox User Agents from getting results from Contile
Tests included, but please try fetching tiles from `/v1/tiles` with various versions of firefox and other UAs to ensure that only firefox gets results. 
Closes #124
=> bug: only permit Firefox UA from querying contile

src/settings.rs, src/web/dockerflow.rs
Closes: #131
Redirects root GET requests to official documentation URL
`curl -v http://{host}` should return a 303 with a `location` header set to the `settings.documentation_url`
Closes #131
┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/CONSVC-170)
=> feat: redirect root requests to official documentation

src/adm/tiles.rs, src/settings.rs, src/web/dockerflow.rs
* Uses setting `adm_timeout`, and defaults to 5 seconds
I suspect that we probably may have different timeouts for various
partners. There is no timeout specified for a default reqwest builder.
requests to ADM should take no longer than 5 seconds in default setting
Closes #139
=> feat: add timeout for calls to ADM service

src/metrics.rs, src/settings.rs, src/tags.rs, src/web/handlers.rs, src/web/middleware/sentry.rs
This adds a `trace_header` setting. This will add the value (if found in
the Headers) to the tags as `header.trace`.
(e.g. if a request has `X-Cloud-Trace-Context: abc123` this will add a
tag with `header.trace: abc123` to the outboud tags for logging and
metrics.)
Ensure the content of the tracing header is sent to metric and logging.
Closes #145
=> feat: add an optional trace header to metrics/logging

src/server/location.rs, src/web/handlers.rs, src/web/test.rs
Changes https://sentry.prod.mozaws.net/operations/contile/issues/11643624/?environment=dev
Issue #149
=> feat: include ip addr for diagnosing mmdb lookup failures

src/server/location.rs, src/settings.rs, src/web/test.rs
only fallback on country (US) when no location info can be found
and recognize mmdb's now always available in tests
Closes #148
=> feat: don't fallback on unknown subdivisions

src/adm/filter.rs, src/adm/tiles.rs, src/error.rs, src/web/handlers.rs, src/web/middleware/sentry.rs, src/web/user_agent.rs
In order to reduce some of the cardinality we're seeing with some sentry errors, it may be a good idea to move some of the data as "tag" info. (e.g. for InvalidUA and ADM Server Errors, we could move the "unique" bits as extra tag info so that we get a better idea of how many events we're seeing without using regular expression tricks.
test included (for InvalidUA at least)
Closes #147
=> bug: make UA name an 'extra' value for Sentry errors.

Cargo.lock, Cargo.toml, src/error.rs, src/web/middleware/sentry.rs, src/web/user_agent.rs
w/ a custom event_from_error for HandlerError
and simplify HandlerError's fmt::Display for sentry's sake
See event improvements in sentry's UI
Closes #158
=> feat: fill in sentry stacktraces

src/adm/tiles.rs, src/server/location.rs, src/web/test.rs
- quiet clippy 1.53.0 warnings
- switch the empty tiles log message to warn! for now (disabling it on
stage/prod w/ the ability to turn it back on)
Re-enabling maxmind on dev/stage
Closes #183
Closes #184
Issue #178
=> feat: fix maxmind country/subdivision to use iso_code

src/server/location.rs, src/web/dockerflow.rs
showing up as a sentry event extra (for debugging purposes)
https://sentry.prod.mozaws.net/operations/contile/issues/11760304/events/67462305/
Closes #192
=> feat: optionally include location info in /__error__

src/adm/filter.rs, src/adm/settings.rs, src/adm/tiles.rs, src/settings.rs, src/web/test.rs
some test cleanup: don't filter out the default "Dunder Mifflin" tile (its
impression host was previously invalid)
New lightweight integration test passes
Closes #216
=> fix: take include_regions into account for filtering 

Cargo.lock, Cargo.toml, src/server/img_storage.rs
Switch from default rust hasher to Blake3
No functional change should happen. You can use the built in unit test by specifying:
```
GOOGLE_APPLICATION_CREDENTIALS=/PathToYourCredentials.json \
CONTILE_TEST_PROJECT=project-name-here \
CONTILE_TEST_BUCKET=bucket-name-here \
cargo test
```
Closes #228.
=> feat: Switch hasher to blake3

src/server/img_storage.rs
This change allow bucket names with `-`
Set `bucket_name` to something with a `-` in it
=> fix: Allow '-' in bucket name

.circleci/config.yml
In bc8d5f29e406f57cfbbae533ee5cbd21cd49e38e the step to write version.json was moved from build to test. This meant that the default version.json in the repository was written to the docker image. Because the default version.json doesn't have a `BUILD_URL` defined, Jenkins has not been deploying contile
=> fix: Write version.json before docker build

.circleci/config.yml
Currently the `deploy` CI job only requires the `build` and `test` jobs. This pull request ensures that an integration test failure blocks the deployment.
Submit a pull request that causes an integration-test failure and verify that CircleCI does **not** run the `deploy` job.
Resolve #238
=> Block deploy CI job on integration-tests

docker-compose.yml
The **21.3.0** release changes the response for invalid query parameter values to a `400 Bad Request`, adds validation to the `sub2` and `country-code` query parameters, and improves the error reporting for integration test failures by including the response content in the error message for unexpected response status codes.
See https://github.com/mozilla-services/contile-integration-tests/releases/tag/21.3.0
Verify that new pull requests use the new Docker images.
NA
=> Upgrade the Docker images for contile-integration-tests

.circleci/config.yml, docker-compose.yml, src/adm/filter.rs, src/adm/settings.rs, src/adm/tiles.rs, src/server/cache.rs, src/settings.rs, src/web/handlers.rs, src/web/mod.rs, src/web/test.rs, src/web/user_agent.rs
This adds `adm_has_legacy_image` which is a JSON list of advertisers
that have "legacy" images pre-loaded into firefox.
Closes #246
Describe these changes.
How should reviewers test?
Closes [link](link).
=> feat: Add `adm_has_legacy_image` setting to filter <v91 tiles

src/server/cache.rs, src/web/handlers.rs
by storing state about active adM requests in the cache
when a request's in the process of populating a cache entry for the first time,
subsequent requests will 503 until it's completed
when a request's in the process of refreshing an existing cache entry,
subsequent requests will return the stale entry until it's completed
and cache empty for BadAdmResponse errors (which haven't happened yet)
Closes #248
=> feat: reduce redundant adM requests

docker-compose.yml, tools/volumes/client/scenarios.yml, tools/volumes/partner/US/WA.yml
This pull request adds a new integration test to verify that Contile successfully returns tiles for a specific country and region.
The integration test docker-compose now mounts the `GeoLite2-City-Test.mmdb` database, which we also use for unit tests, in the Contile Docker container and sets the `X-Forwarded-For` request HTTP header to a random IP address from the range specified by the CIDR network notation in [GeoLite2-City-Test.json](https://github.com/maxmind/MaxMind-DB/blob/main/source-data/GeoLite2-City-Test.json) for `US-WA`.
Verify that the new test `success_country_code_region_code` runs on CI.
NA
=> Add integration test for different regions

src/adm/tiles.rs, src/server/cache.rs, src/web/handlers.rs, tools/volumes/client/scenarios.yml
* Adds `OsFamily` to cache key
* Adds `out=json` to outbound query (to avoid future issues).
* sorted query params to match API list.
@hackebrot: This [includes the latest parameters](https://github.com/mozilla-services/contile/compare/feat/api-2021-08-19?expand=1#diff-5f4dcf145cf76636816065a49a2fbc0e4a52624a4c2109f3547ed1bbb8fa26d7) in the aDM API calls. Integration tests may need modification.
Closes #268
=> chore: API Updates for 2021-08-19

docker-compose.yml, tools/volumes/client/scenarios.yml, tools/volumes/contile/adm_settings.json, tools/volumes/partner/GB/responses.yml
This pull request adds a new integration test to verify that Contile successfully filters tiles based on whether there's an image for the ad provider of a tile shipped with Firefox 90.
- I have added a new ad provider for testing named `DunBroch` which is only returned for in requests from `GB`
- Only `Example ORG` and `Example COM` have  legacy images (see `docker-compose.yml`)
- The first request in the new scenario comes from Firefox 91 and we expect tiles for `DunBroch` as well as `Example COM`
- The second request in the new scenario comes from Firefox 90 and we expect **no** tiles for `DunBroch`
See https://github.com/mozilla-services/contile-integration-tests/pull/64#pullrequestreview-732978460
Verify that the new test `legacy_image_filter` runs on CI.
The feature under test was …
=> Add integration test for legacy image filter

.circleci/config.yml, docker-compose.204.yml, tools/volumes/client/scenarios.yml, tools/volumes/client/scenarios_204.yml
This pull request adds two new integration tests for the `excluded_countries_200` functionality of #290.
Verify that the two new integration tests run and pass on CI.
Resolve #293
=> Add integration tests for 200 OK for excluded countries

docs/API.md
Adds an API.md document describing the API.
Eventually, this should be replaced by a `rustdoc` generated one that's part of the exported docs, but that day is not today.
N/A
=> doc: Add API description document

adm_settings_test.json, integration-tests/volumes/contile/adm_settings.json, src/adm/filter.rs, src/adm/settings.rs, src/web/test.rs
After a second thought, I don't think letting the content partner send whatever URLs to us is a good idea, so I took a crack at refining the existing pathing filter with the following changes:
* Rename the `advertiser_hosts` to `advertiser_urls`
* `advertiser_urls` now takes a list of hosts and path filters (optional). If no path filter is specified, it will only check the host as the current behavior
* Each path filter could be either an "exact-matching" filter or a "prefix-matching" one
* The "value" field for "prefix-matching" filters must contain the trailing "/" in the configuration, otherwise, Contile will panic
The detail of the filtering is documented [here](https://github.com/mozilla-services/contile/pull/311/files#diff-34387244eabf61c959f3a7e535ca04a551c779b9ee645d2e93303c0020f5a …
=> feat: Refine the host & pathing filter

.circleci/config.yml, integration-tests/docker-compose.init_error.yml, integration-tests/volumes/client/scenarios.yml, integration-tests/volumes/client/scenarios_init_error.yml, integration-tests/volumes/contile/adm_settings.json, integration-tests/volumes/contile/adm_settings_init_error.json, integration-tests/volumes/partner/GB/responses.yml
This pull request is a follow-up for #311 and uses that branch as a base. I will rebase this once #311 is merged.
Please see the test scenario descriptions in `integration-tests/volumes/client/scenarios.yml` and let me know if you have any questions about the scenarios.
Note that I've observed unexpected behavior when working this, which I described in https://github.com/mozilla-services/contile/pull/311#issuecomment-961752700. 🚧 
Verify that the following 2 new integration tests run and pass on CI:
* `advertiser_url_path_filter_prefix`
* `advertiser_url_path_filter_exact`
See #311
=> Integration test coverage for path filtering

.circleci/config.yml
This pull request fixes the YAML schema warning for the CircleCI config.
It replaces `=` with `-` and fixes the indentation for the `run` step.
@pjenvey, I believe this job was generated from the skeleton. Do we want to login to DockerHub as part of this job?
Verify that the `Login to Dockerhub` step runs for the `build` job on CI.
Resolve #328
=> bug: fix YAML schema warning for CircleCI config

src/adm/filter.rs, src/adm/tiles.rs, src/web/handlers.rs
to reduce the sentry event cardinality from paths/their query parameters
also include the full audience key & adm_url as extras
Closes #322
Closes #323
=> feat: only include hostname in InvalidHost's err message

.cargo/audit.toml, Cargo.lock, Cargo.toml, src/adm/filter.rs, src/adm/mod.rs, src/adm/settings.rs, src/adm/tiles.rs, src/server/mod.rs, src/settings.rs, src/tags.rs, src/web/handlers.rs, src/web/test.rs
Note: This only reads the brand filter data, other ADM data will require
redeployment.
Closes #324
=> feat: Read ADM settings data from a Google Storage bucket.

integration-tests/docker-compose.yml
See https://github.com/mozilla-services/contile-integration-tests/releases/tag/22.1.0
- test: upgrade the Docker images for contile-integration-tests to 22.1.0
- test: add accepted form-factors for partner API endpoints
=> Upgrade contile-integration-tests Docker images 🤖

integration-tests/volumes/client/scenarios.yml, src/error.rs
Return more useful JSON error messages.
NOTE: We may not want to use the string versions of all errors we're
sending to sentry, so a "simplified" error message is generated.
Closes #177
=> feat: Return JSON error messages

Cargo.lock, Cargo.toml, src/adm/tiles.rs, src/server/cache.rs, src/web/handlers.rs
and kill TilesCache's Deref to dashmap, since we now only expose get and insert
outside of the cache module
Closes #342
=> feat: move cleanup of temp cache states into a ScopeGuard

Cargo.lock, Cargo.toml, src/adm/filter.rs, src/adm/settings.rs, src/server/img_storage.rs, src/server/mod.rs, src/settings.rs, src/web/test.rs
This uses new `mozilla-services/cloud-storage-rs *::*_with()` calls to
pass a `reqwest::Client` object with timeouts.
Closes: #354, CONSVC-1616
=> bug: add timeouts for reqwest calls

src/adm/tiles.rs, src/server/img_storage.rs, src/server/mod.rs
we now refetch them only every 15 minutes (tiles_ttl) or sooner if we know of a
bucket level ttl
Closes #357
=> feat: add a simple image cache to reduce image fetches

Cargo.lock, src/adm/tiles.rs, src/metrics.rs, src/server/img_storage.rs, src/tags.rs, src/web/extractors.rs, src/web/mod.rs, src/web/test.rs
and kill other unused UA metric tags which have too high of cardinality anyway
also tag mobile endpoint requests
Closes #369
=> feat: include os-family and form-factor as metric tags

src/adm/filter.rs, src/adm/settings.rs, src/server/img_storage.rs
=> bug: add check for image_hosts

.circleci/config.yml, src/adm/filter.rs
per https://github.com/mozilla-services/Dockerflow/pull/44
_TAG seems to only fix this issue on tagged builds, whereas _SHA1 should also
solve it on dev builds lacking a tag
and switch the currently unused sccache key to CIRCLE_JOB
Closes #380
=> chore: prefer CIRCLE_SHA1 vs CIRCLE_TAG in circle's cache key

src/adm/filter.rs, src/adm/tiles.rs, src/server/mod.rs, src/web/handlers.rs, src/web/test.rs
This fixes [CONSVC-1794](https://mozilla-hub.atlassian.net/browse/CONSVC-1794), picking it up now since it's blocking the Test Engineering team.
Alternatively, we could also fix this Clippy warning by simply silencing it, but I thought it should be an easy fix by replacing `std::sync::RwLock` with `tokio::sync::RwLock`. That mutable reference of `Tags`, which was used in various places, made this refactor trickier. I ended up using `DashMap`, which provides interior mutation, as the backing store for `Tags` so that we don't need to wrap it into `Arc<RwLock<Tags>>`.
Let me know what you think.
=> refactor: Use async friendly RwLocks in async code paths

smoke-tests/README.md, smoke-tests/client/main.py, smoke-tests/runner/main.py
This changes the runner Cloud Function to return the response content from clients as JSON.
cc @dlactin 
Deploy the Cloud Function, go to Testing and check that reponses from the runner now contain client errors as JSON.
[CONSVC-1795](https://mozilla-hub.atlassian.net/browse/CONSVC-1795)
=> Return JSON in response content for smoke tests

contract-tests/docker-compose.yml
For reference: https://github.com/mozilla-services/contile-integration-tests/releases/tag/22.1.2
[CONSVC-1785](https://mozilla-hub.atlassian.net/browse/CONSVC-1785)
=> Upgrade contile-integration-tests Docker images v22.1.2

test-engineering/contract-tests/partner/Dockerfile, test-engineering/contract-tests/partner/README.md, test-engineering/contract-tests/partner/app/main.py, test-engineering/contract-tests/partner/app/models.py, test-engineering/contract-tests/partner/app/record_keeper.py
Add the `records` endpoint to the partner API with GET and DELETE method support. 
The GET method will return the history of calls made by contile to the partner API. It's intended use is to verify the correctness of contile caching. 
The DELETE method will clear the history of calls made by contile to the partner API. It's intended use is in test teardown.
The records are managed and stored in memory through use of the multiprocessing [SyncManager](https://docs.python.org/3/library/multiprocessing.html#multiprocessing.managers.SyncManager). This necessitates the use of the [gunicorn --preload](https://docs.gunicorn.org/en/stable/settings.html#preload-app) option.
[CONSVC-1279](https://mozilla-hub.atlassian.net/browse/CONSVC-1279) …
=> test: add capability of querying and clearing record of requests to partner API

test-engineering/contract-tests/README.md, test-engineering/contract-tests/client/README.md, test-engineering/contract-tests/client/tests/conftest.py, test-engineering/contract-tests/client/tests/exceptions.py, test-engineering/contract-tests/client/tests/models.py, test-engineering/contract-tests/client/tests/test_contile.py, test-engineering/contract-tests/docker-compose.yml, test-engineering/contract-tests/volumes/client/scenarios.yml, test-engineering/contract-tests/volumes/client/scenarios_204.yml, test-engineering/contract-tests/volumes/client/scenarios_init_error.yml
Add a new step type to the Contile contract tests, allowing for verification of the partner request history during scenario execution.
* add capacity to specify either 'contile' or 'partner' service as request target in scenario step request
* add support for Records content in scenario step response
* add teardown which clears records of contile partner requests between tests
* update README documentation
[CONSVC-1293](https://mozilla-hub.atlassian.net/browse/CONSVC-1293)
=> test: add capability to specify service in client scenarios step

.circleci/config.yml, Dockerfile, src/server/img_storage.rs, src/settings.rs
switching from the deprecated circleci namespace to cimg and pinning
CI's rust version to match the Dockerfile's
also update clippy per 1.63.0
=> chore: update rust (to 1.62.1, the latest circleci image)

Cargo.lock, Cargo.toml, src/adm/filter.rs, src/adm/tiles.rs, src/server/cache.rs, src/settings.rs, src/web/handlers.rs, src/web/middleware/sentry.rs, src/web/test.rs
to render Cache-Control headers in most cases
and fix omissions of stack traces to sentry events
Closes #305
Closes #376
=> feat: add the fallback protocol

src/adm/filter.rs, src/web/test.rs
Currently, we only have metrics for updates for changes that occur for the adm filters. This made it hard to determine whether there was an attempt at an update or whether there were no changes. Added metrics for check attempts.
In addition, changed metric from adm.filter to filter.adm for consistency
=> fix: adm update metrics to be consistent

src/adm/filter.rs, src/adm/settings.rs, src/server/mod.rs
also fix a bug in the updater's handling of all_include_regions
DISCO-2203 & DISCO-2204
Closes #502
Closes #503
=> fix: reduce the work done while holding the updater write lock

src/adm/filter.rs, src/server/mod.rs
The follow-up of #504 to mitigate [this anomaly](https://github.com/mozilla-services/contile/pull/504#discussion_r1071539794).
=> fix: use last object modification timestamp for filter updater

src/web/handlers.rs, src/web/test.rs, test-engineering/contract-tests/volumes/client/scenarios_204.yml
Per the partner's request, we don't want to serve tiles for clients if their form factor (device type) is unknown. 
This fixes [DISCO-2250](https://mozilla-hub.atlassian.net/browse/DISCO-2250).
[DISCO-2250]: https://mozilla-hub.atlassian.net/browse/DISCO-2250?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DISCO-2250] feat: Return 204 for unknown form factors

test-engineering/contract-tests/docker-compose.yml, test-engineering/contract-tests/volumes/partner/responses.yml
Sigh, turns out the test failures were caused by the crappy network latency issues (only in docker-compose) on M1 laptops. Increasing both the connection and adm_request timeouts seemed to work, though it will take a little bit longer to finish all the tests, which is still better than failures.
cc: @Trinaa
=> fix: Fix intermittent contract test failures on M1 laptops

Cargo.lock
Lots of our dependencies are depending on openssl, so I did `cargo update` to update them all.
=> chore: update dependencies for cargo audit

src/adm/tiles.rs, src/web/test.rs
This fixes [DISCO-2293](https://mozilla-hub.atlassian.net/browse/DISCO-2293).
[DISCO-2293]: https://mozilla-hub.atlassian.net/browse/DISCO-2293?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: Add country-code to metric tags for ad fill instrumentation

src/adm/tiles.rs, src/settings.rs, src/web/mock_adm_response1.json, src/web/test.rs, test-engineering/contract-tests/volumes/client/scenarios.yml, test-engineering/contract-tests/volumes/partner/GB/responses.yml
This commit adds an option to separately control the maximum number of tiles returned to Desktop and mobile clients.
Desktop clients use the `adm_max_tiles` setting now, and mobile clients use `adm_mobile_max_tiles` (falling back to `adm_max_tiles`).
=> feat: Add an `adm_mobile_max_tiles` setting (DISCO-2306)

.dockerignore, .gitignore, Makefile, src/server/cache.rs
This change does 2 things
1. Adding a Makefile to run checks and create a coverage report
2. Add some tests to a random file (cache)
This is a first step to getting us higher test coverage to prepare Contile for Rapid Release.
=> Add some commands to run Coverage and Checks locally

src/adm/tiles.rs, src/metrics.rs, src/tags.rs, src/web/test.rs
This closes [DISCO-2346](https://mozilla-hub.atlassian.net/browse/DISCO-2346).
r? @pjenvey for extra eyeballs since this is the first time to use a distribution metric in Contile.
[DISCO-2346]: https://mozilla-hub.atlassian.net/browse/DISCO-2346?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: Add a metric to measure the tile count of adm response

CHANGELOG.md, Cargo.lock, Cargo.toml, test-engineering/contract-tests/volumes/client/scenarios.yml, test-engineering/contract-tests/volumes/client/scenarios_tiles_cache.yml
JIRA: N/A
GitHub: [#547](https://github.com/mozilla-services/contile/issues/547)
Release v1.11.3 for a change with sentry.
=> chore: tag 1.11.3

.circleci/config.yml
JIRA: [DISCO-2278](https://mozilla-hub.atlassian.net/browse/DISCO-2278)
GitHub: #523 
- Add the docker-image-publish-locust job to CI, which automates the encapsulation of the load test solution in a Docker image and registers it on Docker Hub.
[DISCO-2278]: https://mozilla-hub.atlassian.net/browse/DISCO-2278?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DISCO-2278] Update CircleCI to create and register Contile load test Docker image

.circleci/config.yml, CONTRIBUTING.md, PULL_REQUEST_TEMPLATE.md, README.md, test-engineering/load/README.md
JIRA: [DISCO-2277](https://mozilla-hub.atlassian.net/browse/DISCO-2277)
GitHub: [#TODO](https://github.com/mozilla-services/contile/issues/TODO)
In order to facilitate stage and production deployments, as well as to allow contributors to opt-in to load testing on the deployment pipeline, create distinctive Docker Hub publication jobs in the CircleCI workflow. 
Enable signalization to Jenkins via Docker tag assignment, using the following convention:
`^(?P<environment>stage|prod)(?:-(?P<task>\w+)-(?P<onfailure>warn|abort))?-(?P<commit>[a-z0-9]+)$`
**Example Docker image tag name:**
The load test signal is established using text in a git commit. The text should take the form [load test: (abort|warn)]. 
The abort text will prevent a prod deployment should the load test fail. 
The warn text …
=> [DISCO-2277] Deploy stage and production images to Docker Hub

Cargo.lock, Cargo.toml, src/main.rs
GitHub: [sentry-rust#574](https://github.com/getsentry/sentry-rust/issues/574)
so we can keep the crate's default-features in Cargo.toml
(follow up to 976da76a, thanks JR)
=> chore: move disabling of debug-images into code

.circleci/config.yml
JIRA: [DISCO-2333](https://mozilla-hub.atlassian.net/browse/DISCO-2333)
This change runs 2 different workflows for whether the code goes to `main` or if the code runs via `pr`. We don't want to publish images to DockerHub for CI runs on the PR.
I'll need to also update the branch protection rules to use the new workflow name after I get approval:
[DISCO-2333]: https://mozilla-hub.atlassian.net/browse/DISCO-2333?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DISCO-2333] Split up the CircleCI workflow for PR and `main`

.circleci/config.yml
We want to see if this makes the build slightly faster. I also modified the test run to _not_ run all the tests 3 times. 
relates to DISCO-2392
=> Remove dependency on the `build` step to run tests

.circleci/config.yml, PULL_REQUEST_TEMPLATE.md, README.md
JIRA: [DISCO-2280](https://mozilla-hub.atlassian.net/browse/DISCO-2280)
GitHub: [#TODO](https://github.com/mozilla-services/contile/issues/TODO)
In order to empower contributors to skip deployments (example: for documentation changes) and control the flow of changes to staging and production environments, introduce the check-for-deployment and unhold-to-deploy jobs to the Contile CI main-workflow. 
Resource
Example: [Merino CI workflows](https://github.com/mozilla-services/merino-py/blob/main/.circleci/config.yml#L324-L341)
[Adding approval jobs to your CI pipeline](https://circleci.com/blog/adding-approval-jobs-to-your-ci-pipeline/)
Acceptance Criteria
A check-for-deployment job is incorporated into the Contile CI main-workflow
It’s purpose is to detect the “[do not deploy]” text within …
=> [DISCO-2280] Add 'check-for-deployment' and 'unhold-to-deploy' jobs to the Contile CI main-workflow

.circleci/config.yml
JIRA: [DISCO-1786](https://mozilla-hub.atlassian.net/browse/DISCO-1786)
This resolves an issue with `git` being not installed in the Docker image publish job in CircleCI.
[DISCO-1786]: https://mozilla-hub.atlassian.net/browse/DISCO-1786?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DISCO-1786] Switch to different Docker image in CircleCI publish job

.github/dependabot.yml
We want to drop deploying contract test updates because those are run during the PR workflow. We also want to run load tests for updates that involve load tests dependency updates so that we can catch problems with load tests if the dependency breaks something.
=> Update dependabot commit messages with tags [do not deploy]

test-engineering/load/locustfiles/locustfile.py
304 is an expected status code and therefore load tests should not fail then 304s are returned
=> fix: Add 304 an expected status [load test: warn]

.circleci/config.yml
JIRA: [DISCO-2145](https://mozilla-hub.atlassian.net/browse/DISCO-2415)
GitHub: N/A
Fix the wrong code coverage threshold in CI.
[DISCO-2145]: https://mozilla-hub.atlassian.net/browse/DISCO-2145?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DISCO-2415] fix: Fix the code coverage threshold

src/adm/tiles.rs, src/web/handlers.rs, src/web/test.rs, test-engineering/contract-tests/volumes/client/scenarios.yml
JIRA: [DISCO-2419](https://mozilla-hub.atlassian.net/browse/DISCO-2419)
GitHub: N/A
SOV is scoped for Desktop only for this MVP, no need to send SOV settings to other platforms for now.
[DISCO-2419]: https://mozilla-hub.atlassian.net/browse/DISCO-2419?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DISCO-2419] fix: Only include sov for desktop requests

.circleci/config.yml
JIRA: [DISCO-2442](https://mozilla-hub.atlassian.net/browse/DISCO-2442)
GitHub: N/A
- Lesson learned from Merino, update the contract test CI image
[DISCO-2442]: https://mozilla-hub.atlassian.net/browse/DISCO-2442?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DISCO-2442] chore: update contract CI image to ubuntu-2004:2023.04.2

.circleci/config.yml, .github/dependabot.yml, PULL_REQUEST_TEMPLATE.md, README.md
JIRA: [DISCO-2249](https://mozilla-hub.atlassian.net/browse/DISCO-2249)
GitHub: N/A
- Update the Contile CircleCI Workflow
- Remove the unhold-to-deploy job
- Merge the docker-image-publish-stage and docker-image-publish-prod jobs
- Remove the check-for-deployment job
- Update the dependabot configuration
- Update the README.md and PULL_REQUEST_TEMPLATE.md Documentation
[DISCO-2249]: https://mozilla-hub.atlassian.net/browse/DISCO-2249?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DISCO-2249] Delete Contile CI approval task for the production deployment

.cargo/audit.toml, Cargo.lock
JIRA: [DISCO-2455](https://mozilla-hub.atlassian.net/browse/DISCO-2455)
GitHub: N/A
- Whitelisted [RUSTSEC-2021-0145] for atty as it only affects Windows.
- Updated openssl to the latest
[DISCO-2455]: https://mozilla-hub.atlassian.net/browse/DISCO-2455?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DISCO-2455] chore: fix Cargo audit

test-engineering/load/README.md
JIRA: [DISCO-2452](https://mozilla-hub.atlassian.net/browse/DISCO-2452)
GitHub: #336 
During the execution of Merino-py load tests on June 19th 2023, the need to provide an instruction for the **setup** option in the load test script was identified. This applies to Contile as well.
[DISCO-2452]: https://mozilla-hub.atlassian.net/browse/DISCO-2452?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DISCO-2452] Add Instruction for Image Only Deployment (Setup) In Load Test Documentation [load test: abort]

.circleci/config.yml, test-engineering/.gitignore, test-engineering/contract-tests/docker-compose.yml
JIRA: [DISCO-2391](https://mozilla-hub.atlassian.net/browse/DISCO-2391)
GitHub: #606 
- update the CircleCI config
- Use a workspace instead of the cache for persisting the contile Docker image
- According to this [article](https://circleci.com/blog/persisting-data-in-workflows-when-to-use-caching-artifacts-and-workspaces/) the workspace seems the more appropriate solution
- Making this switch resolved instability in contract tests
- remove the setup-sccache, restore-sccache-cache and save-sccache-cache commands
- they seem to be unused? 
- report contract test results to CircleCI to take advantage of insights 
- Note the 'init_error' contract tests can't be reported, since they fail deliberately 
[DISCO-2391]: …
=> [DISCO-2391] Upload Contract Test Results to CircleCI Test Insights

test-engineering/load/README.md, test-engineering/load/kubernetes-config/locust-master-controller.yml, test-engineering/load/kubernetes-config/locust-worker-controller.yml, test-engineering/load/setup_k8s.sh
JIRA: [DISCO-2472](https://mozilla-hub.atlassian.net/browse/DISCO-2472)
GitHub: #350 
- Improve load test setup script by using patterns fixed on constants instead of placeholders
- Update load test README
**Related PR:** https://github.com/mozilla-services/merino-py/pull/363
[DISCO-2472]: https://mozilla-hub.atlassian.net/browse/DISCO-2472?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DISCO-2472] Contile: Load Test Script Modifies Kubernetes Config On First Run Only [load test: warn]

src/settings.rs, src/web/test.rs, test-engineering/contract-tests/volumes/client/scenarios.yml
JIRA: [DISCO-2516](https://mozilla-hub.atlassian.net/browse/DISCO-2516)
GitHub: N/A
Firefox now can handle HTTP 204 properly, Contile can return HTTP 204 for excluded regions. This flips the pref added in #290.
[DISCO-2516]: https://mozilla-hub.atlassian.net/browse/DISCO-2516?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DISCO-2516] fix: Return HTTP 204 for excluded regions

README.md, docs/SUMMARY.md, docs/intro.md, docs/setup.md
JIRA: [DISCO-2506](https://mozilla-hub.atlassian.net/browse/DISCO-2506)
Moved some setup docs into its own separate doc.  Was not sure when the tickets says to call out MaxmindDb whether having it in the architecture diagram was sufficient. Diagram uses the theme "dark" since i found the arrows were hard to see in the default theme against a dark background.
[DISCO-2506]: https://mozilla-hub.atlassian.net/browse/DISCO-2506?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DISCO-2506] Service Overview Page

docs/SUMMARY.md, docs/operations/index.md, docs/operations/rollback.md
JIRA: [DISCO-2513](https://mozilla-hub.atlassian.net/browse/DISCO-2513)
Add some documentation on how we should perform a rollback on Contile.
[DISCO-2513]: https://mozilla-hub.atlassian.net/browse/DISCO-2513?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add rollback documentation for Contile

PULL_REQUEST_TEMPLATE.md
JIRA: [DISCO-2572](https://mozilla-hub.atlassian.net/browse/DISCO-2572)
Remove the GitHub issue link from the Pull Request Templates
[DISCO-2572]: https://mozilla-hub.atlassian.net/browse/DISCO-2572?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DISCO-2572] remove github link from pr template

src/adm/filter.rs, src/adm/settings.rs, src/server/cache.rs, src/settings.rs, src/web/handlers.rs, src/web/test.rs, test-engineering/contract/docker-compose.204.yml, test-engineering/contract/volumes/client/scenarios_204.yml
JIRA: [DISCO-2518](https://mozilla-hub.atlassian.net/browse/DISCO-2518)
This is no longer needed as Firefox 115 and later correctly handle a 204 response.
This reverts #290 and #479.
[DISCO-2518]: https://mozilla-hub.atlassian.net/browse/DISCO-2518?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DISCO-2518]: Drop the excluded_countries_200 setting

.circleci/config.yml, Cargo.lock, Cargo.toml, Dockerfile, src/metrics.rs, src/server/cache.rs, src/settings.rs, src/sov/mod.rs, src/web/middleware/sentry.rs
JIRA: [DISCO-2589](https://mozilla-hub.atlassian.net/browse/DISCO-2589)
Update Rust to 1.74, update all crates, and fix various issues surfaced by the Rust update.
[DISCO-2589]: https://mozilla-hub.atlassian.net/browse/DISCO-2589?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DISCO-2589] Update Rust and dependencies
